spring:
  application:
    name: repaso-api

  hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver

    #local
    url: jdbc:mysql://localhost:3306/repaso
    username: root
    password: $ANtiagoC0106*


    hikari:
      maximum-pool-size: 2
      pool-name: KrakenPool
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
  servlet:
    context-path: /repasochill




